name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency: build

jobs:
  release_pkg:
    runs-on: self-hosted

    strategy:
      matrix:
        include:
          - FREEBSD_VERSION: FreeBSD-14.0-CURRENT
            PFSENSE_VERSION: 2.7
          - FREEBSD_VERSION: FreeBSD-15.0-CURRENT
            PFSENSE_VERSION: 2.8

    steps:
      - uses: actions/checkout@v6

      - name: Setup FreeBSD build VM
        uses: ./.github/actions/setup_vm
        id: setup_vm
        with:
          name: ${{ matrix.FREEBSD_VERSION }}
          snapshot: initial
          domain: actions.pfrest.org
          wait_time: 5

      - name: Build pfSense-pkg-saml2-auth on FreeBSD
        run: |
          /usr/bin/ssh -o StrictHostKeyChecking=no ${{ matrix.FREEBSD_VERSION }}.actions.pfrest.org 'sudo pkill ntpd || true && sudo ntpdate pool.ntp.org || true'
          /usr/local/bin/python3 tools/make_package.py --host ${{ matrix.FREEBSD_VERSION }}.actions.pfrest.org --branch ${{ github.sha }} --tag ${{ github.ref_name }} --filename pfSense-${{ matrix.PFSENSE_VERSION }}-pkg-saml2-auth.pkg

      - name: Teardown FreeBSD build VM
        if: "${{ always() }}"
        uses: ./.github/actions/teardown_vm
        with:
          name: ${{ matrix.FREEBSD_VERSION }}
          snapshot: initial

      - name: Release package
        uses: softprops/action-gh-release@v2
        with:
          files: pfSense-${{ matrix.PFSENSE_VERSION }}-pkg-saml2-auth.pkg

  release_docs:
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease }}
    needs:
      - release_pkg
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Make website directory
        run: mkdir ./www

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build mkdocs site
        run: |
          python3 -m pip install -r ./requirements-dev.txt
          python3 -m mkdocs build
          mv ./site/* ./www/

      - name: Build PHP reference documentation
        run: |
          mkdir ./www/php-docs
          wget https://phpdoc.org/phpDocumentor.phar
          chmod +x phpDocumentor.phar
          ./phpDocumentor.phar
          mv ./.phpdoc/build/* ./www/php-docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: "./www"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
